version: '3.5' 

services:
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443

    frontend:
        build: ../2.3/example-frontend
    backend:
        build: ../2.3/example-backend
        environment:
            - REQUEST_ORIGIN=http://localhost:5000
            - REDIS_HOST=redis
            - POSTGRES_HOST=db

    redis:
        image: redis
        
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
