version: '3.5' 

services:
    frontend:
        build: 
            context: ../2.3/example-frontend
            dockerfile: Dockerfile
            args:
                REACT_APP_BACKEND_URL: http://localhost:8080
        ports:
            - 5000:5000
    backend:
        build: ./example-backend
        environment:
            - REQUEST_ORIGIN=http://localhost:5000
        ports:
            - 8080:8080
